<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body onload="redirect()">
<?php 
require_once('Mongo_config.php');
require_once 'razorpay-php/Razorpay.php';

global $manager;
global $Mongo_database;

session_start();
error_reporting(0);

$_SESSION['tokenid'];

$_SESSION['user_name'];
$_SESSION['user_name_phone'];
$_SESSION['user_postal_code'];
$_SESSION['user_name_whatsappmessagesId'];
$_SESSION['wpnumb'];
$_SESSION['user_name_orderNum'];
$_SESSION['user_details'];
$_SESSION['tm'];

date_default_timezone_set("Asia/Kolkata");
$created = date("Y-m-d::H:i:s");

// https://pages.razorpay.com/pl_GPtkTQRLV5xeoF/view
// add api

use Razorpay\Api\Api;

$api_key = "rzp_test_DSK0mPgSFBQAZk";

$api_secret = "KOCu4NLTwdCktZagKpdCIfwK";

$api = new Api($api_key, $api_secret);

//  Fetching data from ajax get

?>    

<script src="https://code.jquery.com/jquery-3.5.0.js"></script>



<form action="success.php" method="POST">
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="<?php echo $api_key; ?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="<?php echo $_SESSION['tm'] * 100;?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"//You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-id="<?php echo rand(00000000,99999999);?>"//Replace with the order_id generated by you in the backend.
    data-buttontext="Pay with Razorpay"
    data-name="Brilliant Infotech"
    data-description="Grocery Bill Payment!"
    data-prefill.name="<?php echo $_SESSION['user_details'][0].' '. $_SESSION['user_details'][1];?>"
    data-theme.color="#e31837"
></script>
<input type="hidden" custom="Hidden Element" name="hidden">
<script type="text/javascript">
	function redirect(){
	   document.querySelectorAll("input[type='submit']")[0].click();
	}
</script>
</form>



</body>
</html>